language: python
python:
  - "3.4"
install:
  - pip install coverage coveralls pylint pep8
script:
  - nosetests --with-coverage --cover-inclusive --exclude='.*integration.*'
after_success:
  - coveralls
